### ISSUE TITLE
What firmware is expected?

### ISSUE THREAD

**Issue by moscito1010** [gmag11/esp32_mqtt_eq3#1]
What firmware is expected? 
I have the firmware with the 4 digit pin code.
Homeassistant shows me the "controller" but no values are output. The temperature, valve and battery data are shown as unknown.
The ESP shows the thermostats correctly on its website and I can also use it to control the thermostats.
With the tool "mqtt explorer" I can also see what is happening there. No current data for e.g. the temperature is displayed there either.

**Comment by inforsgit** [comment]
I have the same issue but I don't think it is a firmware problem because the local webpage of the device works without an issue.

**Comment by moscito1010** [comment]
I switched from the original to this fork. For this I used the function on the ESP website and did not flash it again via USB. But that shouldn't matter, the webtool works 100%

**Comment by inforsgit** [comment]
I think I see the issue - if you look at what HA is expecting, I think it expects the controller to be named "eq3_":
![image](https://user-images.githubusercontent.com/1859173/213926868-5b636bc3-41bd-4be0-8f6b-82209ff15117.png)

**Comment by inforsgit** [comment]
Confirmed 👍 - its seems that you have to set the "MQTT ID" on the Configuration page of the web interface to "eq3_" or it won't work. I guess this a fix that could be implemented in the code @gmag11? Thanks!!

![image](https://user-images.githubusercontent.com/1859173/213927182-7e1d5914-9dd1-4165-bfb2-b2c8691d2182.png)

**Comment by moscito1010** [comment]
I changed it but still no data is displayed
![ha](https://user-images.githubusercontent.com/75945899/213929276-2c531a9a-483c-4427-b0b5-4904fc419696.JPG)

**Comment by inforsgit** [comment]
For me I had to send a command to the TRV (like switching it to auto) to prompt generation of a status message…then it showed connected on HA with data after 30 seconds or so.

**Comment by moscito1010** [comment]
sorry but what is TRV please?

**Comment by inforsgit** [comment]
The thermostat valve…just change a setting on it like “Auto” or “Heat” and it should connect.

**Comment by moscito1010** [comment]
it works...

**Comment by gmag11** [comment]
Yes, the valve do not actively send any data. And there is no command to request configuration, you need to ask any supported command and you will get the data.
